### ISSUE TITLE
Training -Validation and test splits

### ISSUE THREAD

**Issue by 7wik** [abhaydoke09/Bilinear-CNN-TensorFlow#33]
Can you please provide the ratio in which you have divided the dataset into training, validation, test sets respectively, in that order?

**Comment by abhaydoke09** [comment]
It's a standard data set. [FGVC-Aircraft Benchmark](http://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft/).
They provide you the train and test data. Please follow their website.
