### ISSUE TITLE
why phi_I need to divide by 784.0?

### ISSUE THREAD

**Issue by YunCL** [abhaydoke09/Bilinear-CNN-TensorFlow#4]
self.phi_I = tf.divide(self.phi_I,784.0)  
I don't understand this code.And th paper about it is also not found

**Comment by abhaydoke09** [comment]
It's used for the normalization. 
Paper is http://vis-www.cs.umass.edu/bcnn/docs/bcnn_iccv15.pdf

When we are having an outer product of two matrices with shapes (512 x 784) and (784 x 512), we are summing over the 784 dimension. So you can normalize that summation to keep values from taking huge values.

**Comment by YunCL** [comment]
Thanks for your answer. I have understood it.
