### ISSUE TITLE
problem with data size

### ISSUE THREAD

**Issue by techzhou** [abhaydoke09/Bilinear-CNN-TensorFlow#5]
I am newbie. I got

>  File "bcnn_DD_woft.py", line 382, in <module>
    val_loss += sess.run(loss, feed_dict={imgs: batch_val_x, target: batch_val_y})
ValueError: Cannot feed value of shape (10, 224, 224, 3) for Tensor 'Placeholder:0', which has shape '(?, 448, 448, 3)'

Is data size wrong? train/test/val need same size?

**Comment by abhaydoke09** [comment]
We are resizing all images to 448 x 448 for better fine grained visual features.
You need to resize your images to 448 x 448.
Please let me know when it works!!

**Comment by techzhou** [comment]
Yes！It works. thank u
